### ISSUE TITLE
All photos in the public domain?

### ISSUE THREAD

**Issue by mwweinberg** [LibraryOfCongress/newspaper-navigator#3]
First, I want to say that this is a fantastic project and I am very excited about it.

I do have a quick question about rights.  In asking it, I recognize that thinking about the rights status of old newspapers may not be the most exciting part of this project for most people.

The first answer in the about page currently says "All Newspaper Navigator photos in the app and dataset are in the public domain!"  Does that mean that the LoC has done clearances on all of the photos in the dataset?  I (think I) understand that the navigator is not asserting new rights in the digitization or the collection, which means that all photos that are in the public domain are still in the public domain.  However, unless some additional work has been done, it is likely that many images from 1925 on are still protected by copyright.  

If this is the case, I would be happy to help come up with clarifying language for the FAQ.  I was thinking about submitting this as a pull request, but it seemed prudent to check first before simply assuming a state of affairs.

thanks again for building this!

**Comment by jaimemears** [comment]
Hi Michael - thanks for this. We didnt receive a notification of your issue and only now discovered it as we are putting the repo into archive mode. We updated the language on the about page of the application to more accuratley reflect the nuances of PD at the newspaper page level vs image-level copyright restrictions. See https://news-navigator.labs.loc.gov/search/about

As of now, no further development of this experiment is planned. In the event there are next lives for this experiment, we'll announce them on twitter @LC_Labs and on our listserv which you can sign up for at labs.loc.gov.
